### ISSUE TITLE
All deploys use the same port

### ISSUE THREAD

**Issue by s-matic** [exoframejs/exoframe#121]
When deploying any project with exoframe is uses the same 80/tcp port for all of the containers. Thus making every deploy after the first one unusable, do you have any idea on how to resolve this issue?

**Comment by yamalight** [comment]
All containers indeed [expose](https://docs.docker.com/engine/reference/builder/#expose) port 80 by default. 
That should not be the problem though since [Traefik](https://traefik.io/) is what _listens_ on port 80 and routes all the requests to containers.

Could you give an example of deployment(s) you are having problems with?

**Comment by yamalight** [comment]
since there's no follow up, I'm going to close the issue. feel free to re-open it if you have more questions.
