### ISSUE TITLE
Swarm deployment on worker node fails

### ISSUE THREAD

**Issue by benmerckx** [exoframejs/exoframe#176]
I followed the AWS tutorial loosely for setting up a docker swarm locally. If I deploy projects and swarm decides they're run on the master node everything is fine. However if they are started on another node the deploy is rejected as it seems the built docker image is only available on the master node.

**Comment by yamalight** [comment]
Unfortunately this is a current limitation of exoframe. Swarm support was originally added for internal project that needed recipes deployment to swarm (that works fine since recipes typically pull existing images).
Adding image sync across swarm nodes is planned and there's a ticket to track the status: https://github.com/exoframejs/exoframe/issues/145 (PRs welcome if you want to tackle that)

**Comment by benmerckx** [comment]
Thanks, that explains it!
