### ISSUE TITLE
How to use a custom traefik?

### ISSUE THREAD

**Issue by w4tsn** [exoframejs/exoframe#281]
Hey there!

I've already a traefik running on my server and I'd like to use this one instead of managing it through exoframe. I've disabled exoframes management of traefik but it seems that the labels are not yet compatible with my traefik 2.x container.

Does exoframe assign correct labels for routing etc. even though I've turned off traefik management?

**Comment by yamalight** [comment]
It should work, yes.
There's two ways to make Exoframe work with your custom traefik:
1. Make sure to start Exoframe on same network as traefik, and tell Exoframe to use that network by setting `exoframeNetwork: 'traefik-net'` in server config
2. Alternatively you can connect your traefik to `exoframe` docker network so that it picks up all new containers started by Exoframe
3. (optional) You can also tell Exoframe to use your traefik by setting `traefikName: 'my-traefik'` in [server config](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md)

**Comment by w4tsn** [comment]
Ah, I now see that the labels are present and that they are in the same network. The problem is however, that the labels are traefik v1 but I'm using traefik v2. Where do I configure this? Is this set in a template or something?

I'm managing an exoframe instance of someone else, so I might be missing something simple :)

**Comment by w4tsn** [comment]
Nvm. I've not paid attention to the exoframe server version. It was pinned to 5.0.4. I most probably just have to upgrade it to the latest version.

**Comment by yamalight** [comment]
Yep, you just need to upgrade to v6 :)

**Comment by w4tsn** [comment]
Ok, so I'm getting close. Thank you for the fast responses by the way :+1: 

The problem now is, that I'm using TLS letsencrypt with my traefik and I'm now missing the respective middlewares that enable my TLS config for containers. How do I add these to the containers?

**Comment by w4tsn** [comment]
It would still be interesting to know, if it's possible to define custom middlewares for the containers

**Comment by yamalight** [comment]
@w4tsn you can do both - either just add middlewares in-place using labels, or use `middlewares` property in project config to apply existing ones (see [project config](https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#project-config-file) docs for examples)
